services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bin/dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/tracker_development
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    command: npx expo start
    ports:
      - "8081:8081"
    volumes:
      - ./mobile:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - backend

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tracker_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
